server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/assignment
    defaultUrl: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    base-package: nl.living.it.assignment.model
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        jdbc:
          lob:
            non_contextual_creation: true